//= require ./2_level/escape.js
//= require ./2_level/fetchs.js
//= require ./2_level/lib/USTORE.js
//= require ./2_level/lib/jconfirmaction.jquery.js
//= require ./2_level/lib/jquery.notifyBar.js
//= require ./2_level/lib/jquery.pagination.js
//= require ./2_level/lib/jquery.query.js
//= require ./2_level/lib/jquery.scrollTo.js
//= require ./2_level/lib/jquery.swfobject.1-1-1.min.js
//= require ./2_level/valid/base.js
//= require ./2_level/valid/re.js
//= require ./2_level/valid/valid.js
//= require ./2_level/view/base.js
//= require ./2_level/view/channel_info_chl_tmpl.coffee
//= require ./2_level/view/channel_info_user_tmpl.coffee
//= require ./2_level/view/channel_info_z.js
//= require ./2_level/view/input_home.js
//= require ./2_level/view/notice.js
//= require ./2_level/view/remark_tmpl.coffee
//= require ./2_level/view/remark_z.js
//= require ./2_level/view/tag.js
//= require ./2_level/view/timeline.js
//= require ./2_level/view/tongues.js
//= require ./2_level/view/toplink.js
//= require ./2_level/view/tweet_tmpl.coffee
//= require ./2_level/view/tweet_u.js
//= require ./2_level/view/ueditor.js
//= require ./widget/0_base.js
//= require ./widget/AutoHeightTextarea.js
//= require ./widget/ChannelName.js
//= require ./widget/DayTile.js
//= require ./widget/LikeButton.js
//= require ./widget/NativeSelectChannel.js
//= require ./widget/PicFullScreen.js
//= require ./widget/SelectChannelBox.js
//= require ./widget/ShortCut.js
//= require ./widget/TinyFollowButton.js
//= require ./widget/cursor_end.js
//= require ./widget/image_loading.js
//= require ./widget/loading.js
//= require ./widget/purge.js
//= require ./widget/smile_dropdown.js
//= require ./widget/toggler.js
//= require ./widget/toggler_click_close.js

//= require ./load_2.js
//= require _home.js

});//end of loadit 

App.trigger('app_ready');